//! GitHub-flavored Markdown report.

use crate::compare::{DiffReport, Verdict};
use crate::report::{fmt_d, fmt_ns, fmt_pct};

#[must_use]
pub fn render(report: &DiffReport) -> String {
    let mut out = String::new();
    out.push_str("# benchdiff report\n\n");
    out.push_str(&format!(
        "**Baseline:** `{}`  \n**Alpha:** `{}`  \n**Min change:** `{:.1}%`  \n**Correction:** `{}`\n\n",
        report.baseline_label,
        report.alpha,
        report.min_relative_change * 100.0,
        report.correction,
    ));

    out.push_str(&format!(
        "**Summary:** {} regression(s), {} improvement(s), {} unchanged\n\n",
        report.regressions(),
        report.improvements(),
        report.unchanged(),
    ));

    out.push_str("| | benchmark | baseline | current | Δ | p | d | verdict |\n");
    out.push_str("|---|---|---:|---:|---:|---:|---:|---|\n");

    for row in &report.rows {
        let (emoji, verdict) = match row.verdict {
            Verdict::Regression => (":x:", "regression"),
            Verdict::Improvement => (":white_check_mark:", "improvement"),
            Verdict::Unchanged => (":white_circle:", "unchanged"),
            Verdict::MissingFromCurrent => (":ghost:", "missing"),
            Verdict::NewInCurrent => (":sparkles:", "new"),
            Verdict::Ignored => (":mute:", "ignored"),
            Verdict::Insufficient => (":warning:", "insufficient"),
        };
        let p = if row.p_value >= 0.9999 {
            "—".to_string()
        } else if row.p_value < 0.0001 {
            "&lt;1e-4".to_string()
        } else {
            format!("{:.4}", row.p_value)
        };
        let d = fmt_d(row.cohens_d);
        // Render the benchmark name as inline code with a fence long enough
        // to survive any embedded backticks. CommonMark says "A backslash
        // escape ... does not work in code spans" — so the previous
        // `\`-escape produced a broken code span and a stray closing
        // backtick. The robust trick: pick a fence of N+1 backticks where
        // N is the longest backtick run in the name, and pad with spaces.
        let name_cell = render_name_cell(&row.name);
        out.push_str(&format!(
            "| {emoji} | {} | {} | {} | {} | {} | {} | {} |\n",
            name_cell,
            fmt_ns(row.baseline_mean_ns),
            fmt_ns(row.current_mean_ns),
            fmt_pct(row.rel_change),
            p,
            d,
            verdict,
        ));
    }

    out.push('\n');
    out.push_str("<sub>Generated by [benchdiff-rs](https://github.com/JSLEEKR/benchdiff-rs).</sub>\n");
    out
}

/// Format a benchmark name as a Markdown table cell.
///
/// Benchmark names can legitimately contain characters that would corrupt a
/// pipe table:
///
/// - `|` would split a cell.
/// - `` ` `` would corrupt an inline code span (CommonMark forbids backslash
///   escaping inside code spans).
/// - `\n` / `\r` would break the row entirely (hyperfine commands can be
///   multi-line shell strings).
///
/// We render the name as inline code wrapped in a backtick fence longer than
/// any embedded backtick run, with single-space padding (CommonMark trims
/// exactly one leading/trailing space from a code span when both ends are
/// padded). Newlines are pre-replaced with literal `\n`/`\r` so the row stays
/// on one line. Pipes are escaped with a leading backslash.
#[must_use]
fn render_name_cell(name: &str) -> String {
    // Step 1: flatten newlines so the row never breaks. Use an escaped
    // sequence the user can recognize. Do this BEFORE counting backticks
    // because the original string is multi-line.
    let flat: String = name
        .chars()
        .map(|c| match c {
            '\n' => '↵',
            '\r' => ' ',
            other => other,
        })
        .collect();

    // Step 2: escape pipes. Outside a code span, `\|` works fine in GFM
    // tables. Inside the code span we'll handle them differently.
    // We still keep the name inside a code span for typographic consistency
    // when it has no backticks; otherwise we drop the code span and escape
    // the pipes with backslashes.
    if !flat.contains('`') {
        let escaped = flat.replace('|', "\\|");
        return format!("`{escaped}`");
    }

    // Step 3: pick a fence longer than any embedded backtick run.
    let max_run = longest_backtick_run(&flat);
    let fence: String = std::iter::repeat('`').take(max_run + 1).collect();
    // Pad with single spaces so the fence and the content are unambiguous
    // even if the content starts/ends with a backtick. Pipes inside the
    // code span cannot be backslash-escaped (same reason as backticks),
    // so we replace them with `\u{2758}` (LIGHT VERTICAL BAR) which renders
    // visually identically and does NOT split the table cell.
    let inside = flat.replace('|', "\u{2758}");
    format!("{fence} {inside} {fence}")
}

/// Length of the longest run of consecutive backticks in `s`.
fn longest_backtick_run(s: &str) -> usize {
    let mut max = 0usize;
    let mut cur = 0usize;
    for c in s.chars() {
        if c == '`' {
            cur += 1;
            if cur > max {
                max = cur;
            }
        } else {
            cur = 0;
        }
    }
    max
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compare::{DiffRow, Verdict};

    fn row(name: &str, verdict: Verdict, rel: f64) -> DiffRow {
        DiffRow {
            name: name.into(),
            baseline_mean_ns: 100.0,
            current_mean_ns: 100.0 * (1.0 + rel),
            n_baseline: 10,
            n_current: 10,
            rel_change: rel,
            p_value: 0.001,
            cohens_d: 2.0,
            verdict,
        }
    }

    fn rep(rows: Vec<DiffRow>) -> DiffReport {
        DiffReport {
            baseline_label: "v1".into(),
            alpha: 0.05,
            min_relative_change: 0.05,
            correction: "none".into(),
            rows,
        }
    }

    #[test]
    fn renders_header_and_table() {
        let r = rep(vec![row("foo", Verdict::Regression, 0.5)]);
        let s = render(&r);
        assert!(s.starts_with("# benchdiff report"));
        assert!(s.contains("| benchmark |"));
        assert!(s.contains(":x:"));
        assert!(s.contains("foo"));
    }

    #[test]
    fn renders_summary_counts() {
        let r = rep(vec![
            row("a", Verdict::Regression, 0.5),
            row("b", Verdict::Improvement, -0.5),
            row("c", Verdict::Unchanged, 0.0),
        ]);
        let s = render(&r);
        assert!(s.contains("1 regression"));
        assert!(s.contains("1 improvement"));
        assert!(s.contains("1 unchanged"));
    }

    #[test]
    fn escapes_pipes_in_name() {
        let r = rep(vec![row("foo|bar", Verdict::Unchanged, 0.0)]);
        let s = render(&r);
        // No-backtick path: backslash-escaped pipe inside an inline code span.
        assert!(s.contains("`foo\\|bar`"));
    }

    #[test]
    fn name_with_backtick_uses_longer_fence() {
        // eval-D regression test: the previous implementation tried to
        // backslash-escape the backtick, which CommonMark explicitly does
        // not honour inside a code span. The result was a corrupted row
        // with a stray closing backtick. The fix is to widen the fence.
        let r = rep(vec![row("a`b", Verdict::Unchanged, 0.0)]);
        let s = render(&r);
        // Must contain the name surrounded by a double-backtick fence
        // (one backtick in the name → fence length 2).
        assert!(
            s.contains("`` a`b ``"),
            "expected widened fence around name, got:\n{s}"
        );
        // Crucially: the table row must not be broken across multiple lines.
        let row_lines: Vec<&str> = s.lines().filter(|l| l.contains("a`b")).collect();
        assert_eq!(
            row_lines.len(),
            1,
            "name with backtick split the row into multiple lines"
        );
    }

    #[test]
    fn name_with_double_backtick_uses_triple_fence() {
        let r = rep(vec![row("x``y", Verdict::Unchanged, 0.0)]);
        let s = render(&r);
        assert!(
            s.contains("``` x``y ```"),
            "expected triple-backtick fence, got:\n{s}"
        );
    }

    #[test]
    fn name_with_newline_stays_on_one_row() {
        // eval-D regression test: hyperfine commands can contain literal
        // newlines (multi-line shell strings). The pre-fix renderer let
        // them straight into the markdown table, which broke the row.
        let r = rep(vec![row("line1\nline2", Verdict::Unchanged, 0.0)]);
        let s = render(&r);
        // Should be exactly one table row mentioning the (transformed) name.
        let row_lines: Vec<&str> = s
            .lines()
            .filter(|l| l.contains("line1") || l.contains("line2"))
            .collect();
        assert_eq!(
            row_lines.len(),
            1,
            "newline in name split the row, got:\n{s}"
        );
        // The transformation symbol ↵ must appear so the original newline
        // is still visible to the reader.
        assert!(s.contains('↵'));
    }

    #[test]
    fn name_with_pipe_inside_code_fence() {
        // When the name contains a backtick (forcing the code-span path)
        // AND a pipe, the pipe must be replaced with a non-table-splitting
        // glyph because backslash escaping doesn't work inside code spans.
        let r = rep(vec![row("a`b|c", Verdict::Unchanged, 0.0)]);
        let s = render(&r);
        let row_lines: Vec<&str> = s.lines().filter(|l| l.contains("a`b")).collect();
        assert_eq!(row_lines.len(), 1, "pipe split the row inside code span");
        // U+2758 LIGHT VERTICAL BAR replaces the literal pipe.
        assert!(s.contains('\u{2758}'));
    }

    #[test]
    fn longest_backtick_run_counts() {
        assert_eq!(longest_backtick_run(""), 0);
        assert_eq!(longest_backtick_run("foo"), 0);
        assert_eq!(longest_backtick_run("a`b"), 1);
        assert_eq!(longest_backtick_run("a``b"), 2);
        assert_eq!(longest_backtick_run("`````"), 5);
        assert_eq!(longest_backtick_run("`a`b``c"), 2);
    }

    #[test]
    fn contains_footer_credit() {
        let s = render(&rep(vec![]));
        assert!(s.contains("benchdiff-rs"));
    }

    #[test]
    fn emoji_per_verdict() {
        let s = render(&rep(vec![
            row("r", Verdict::Regression, 0.1),
            row("i", Verdict::Improvement, -0.1),
            row("u", Verdict::Unchanged, 0.0),
            row("m", Verdict::MissingFromCurrent, 0.0),
            row("n", Verdict::NewInCurrent, 0.0),
            row("g", Verdict::Ignored, 0.0),
            row("s", Verdict::Insufficient, 0.0),
        ]));
        for e in [":x:", ":white_check_mark:", ":white_circle:", ":ghost:",
                  ":sparkles:", ":mute:", ":warning:"] {
            assert!(s.contains(e), "missing emoji {e}");
        }
    }
}
