//! GitHub-flavored Markdown report.

use crate::compare::{DiffReport, Verdict};
use crate::report::{fmt_d, fmt_ns, fmt_pct};

#[must_use]
pub fn render(report: &DiffReport) -> String {
    let mut out = String::new();
    out.push_str("# benchdiff report\n\n");
    out.push_str(&format!(
        "**Baseline:** `{}`  \n**Alpha:** `{}`  \n**Min change:** `{:.1}%`  \n**Correction:** `{}`\n\n",
        report.baseline_label,
        report.alpha,
        report.min_relative_change * 100.0,
        report.correction,
    ));

    out.push_str(&format!(
        "**Summary:** {} regression(s), {} improvement(s), {} unchanged\n\n",
        report.regressions(),
        report.improvements(),
        report.unchanged(),
    ));

    out.push_str("| | benchmark | baseline | current | Δ | p | d | verdict |\n");
    out.push_str("|---|---|---:|---:|---:|---:|---:|---|\n");

    for row in &report.rows {
        let (emoji, verdict) = match row.verdict {
            Verdict::Regression => (":x:", "regression"),
            Verdict::Improvement => (":white_check_mark:", "improvement"),
            Verdict::Unchanged => (":white_circle:", "unchanged"),
            Verdict::MissingFromCurrent => (":ghost:", "missing"),
            Verdict::NewInCurrent => (":sparkles:", "new"),
            Verdict::Ignored => (":mute:", "ignored"),
            Verdict::Insufficient => (":warning:", "insufficient"),
        };
        let p = if row.p_value >= 0.9999 {
            "—".to_string()
        } else if row.p_value < 0.0001 {
            "&lt;1e-4".to_string()
        } else {
            format!("{:.4}", row.p_value)
        };
        let d = fmt_d(row.cohens_d);
        out.push_str(&format!(
            "| {emoji} | `{}` | {} | {} | {} | {} | {} | {} |\n",
            escape_md(&row.name),
            fmt_ns(row.baseline_mean_ns),
            fmt_ns(row.current_mean_ns),
            fmt_pct(row.rel_change),
            p,
            d,
            verdict,
        ));
    }

    out.push('\n');
    out.push_str("<sub>Generated by [benchdiff-rs](https://github.com/JSLEEKR/benchdiff-rs).</sub>\n");
    out
}

fn escape_md(s: &str) -> String {
    s.replace('|', "\\|").replace('`', "\\`")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compare::{DiffRow, Verdict};

    fn row(name: &str, verdict: Verdict, rel: f64) -> DiffRow {
        DiffRow {
            name: name.into(),
            baseline_mean_ns: 100.0,
            current_mean_ns: 100.0 * (1.0 + rel),
            n_baseline: 10,
            n_current: 10,
            rel_change: rel,
            p_value: 0.001,
            cohens_d: 2.0,
            verdict,
        }
    }

    fn rep(rows: Vec<DiffRow>) -> DiffReport {
        DiffReport {
            baseline_label: "v1".into(),
            alpha: 0.05,
            min_relative_change: 0.05,
            correction: "none".into(),
            rows,
        }
    }

    #[test]
    fn renders_header_and_table() {
        let r = rep(vec![row("foo", Verdict::Regression, 0.5)]);
        let s = render(&r);
        assert!(s.starts_with("# benchdiff report"));
        assert!(s.contains("| benchmark |"));
        assert!(s.contains(":x:"));
        assert!(s.contains("foo"));
    }

    #[test]
    fn renders_summary_counts() {
        let r = rep(vec![
            row("a", Verdict::Regression, 0.5),
            row("b", Verdict::Improvement, -0.5),
            row("c", Verdict::Unchanged, 0.0),
        ]);
        let s = render(&r);
        assert!(s.contains("1 regression"));
        assert!(s.contains("1 improvement"));
        assert!(s.contains("1 unchanged"));
    }

    #[test]
    fn escapes_pipes_in_name() {
        let r = rep(vec![row("foo|bar", Verdict::Unchanged, 0.0)]);
        let s = render(&r);
        assert!(s.contains("foo\\|bar"));
    }

    #[test]
    fn contains_footer_credit() {
        let s = render(&rep(vec![]));
        assert!(s.contains("benchdiff-rs"));
    }

    #[test]
    fn emoji_per_verdict() {
        let s = render(&rep(vec![
            row("r", Verdict::Regression, 0.1),
            row("i", Verdict::Improvement, -0.1),
            row("u", Verdict::Unchanged, 0.0),
            row("m", Verdict::MissingFromCurrent, 0.0),
            row("n", Verdict::NewInCurrent, 0.0),
            row("g", Verdict::Ignored, 0.0),
            row("s", Verdict::Insufficient, 0.0),
        ]));
        for e in [":x:", ":white_check_mark:", ":white_circle:", ":ghost:",
                  ":sparkles:", ":mute:", ":warning:"] {
            assert!(s.contains(e), "missing emoji {e}");
        }
    }
}
